name: Docker Image CI
# Faig login a Dockerhub - necessari generar Token a DockerHub
# Faig build d ela imatge i la pujo a Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  dcompanyestall/githubactions_cas1:v1
      
